name: reproduce-cfc
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - numpy=1.26.3
  - numpy-base=1.26.3
  - pip=23.3.1
  - python=3.10.13
  - pytorch-cuda=11.8
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - pip:
    - beautifulsoup4==4.12.2
    - chardet==5.2.0
    - charset-normalizer==3.3.2
    - contourpy==1.2.0
    - cplex==22.1.1.0
    - cycler==0.12.1
    - docplex==2.25.236
    - fonttools==4.47.2
    - fsspec==2023.12.2
    - gdown==4.7.1
    - idna==3.6
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - kmeans-gpu==0.0.5
    - kmeans-pytorch==0.3
    - kmedoids==0.5.0
    - matplotlib==3.8.2
    - networkx==3.2.1
    - pandas==2.1.4
    - pillow==10.2.0
    - protobuf==4.25.2
    - pulp==2.8.0
    - pyckmeans==0.9.4
    - pyparsing==3.1.1
    - python-mnist==0.7
    - pytz==2023.3.post1
    - scikit-learn==1.3.2
    - scipy==1.11.4
    - seaborn==0.13.1
    - soupsieve==2.5
    - threadpoolctl==3.2.0
    - tqdm==4.66.1
    - tzdata==2023.4
    - urllib3==2.1.0
    - zoopt==0.4.2
